version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    container_name: nest_app
    ports:
      - "${APP_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - MAIL_HOST=${MAIL_HOST}
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn start:dev
    depends_on:
      - mongo
      - redis
      - mailhog
    networks:
      - app-network

  mongo:
    build:
      context: ./.docker/mongo
    container_name: nest_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret123

  redis:
    image: redis:latest
    container_name: nest_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: nest_mailhog
    ports:
      - "8025:8025"
    networks:
      - app-network

  nginx:
    build:
      context: ./.docker/nginx
    container_name: nest_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  queue:
    build:
      context: .
      dockerfile: .docker/queue/Dockerfile
    container_name: nest_queue
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
    networks:
      - app-network
    volumes:
      - ./:/app
    working_dir: /app

networks:
  app-network:

volumes:
  mongo_data:
