export const ERROR_CODE = {
  AUTHORIZATION: 'AUTHORIZATION',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  ERROR_SYSTEM: 'ERROR_SYSTEM',

  OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
};
